cookie:
  expiry_days: 30
  key: clave_secreta_123
  name: asistente_notas
credentials:
  usernames:
    jdavid:
      email: jdavidquinteroh@gmail.com
      name: Juan David
      password: $2b$12$ppBpDUulhUWSSu6Cc5efk.T2626LXNu5kMBQcSNfpF9uU1Ir0Y7JG
    jdavidq:
      email: jdavidquinteroh@gmail.com
      name: juan quintero
      password: $2b$12$l5YKYOb5HYvFGh/uE2KAk.vdefSuLEOFG41ylclAZl1W6TgfRhni.
